#include <algorithm>
#include <cstdint>
#include <cstring>
#include <ctime>
#include <fstream>
#include <iostream>
#include <openssl/rand.h>
#include <random>
#include <sodium.h>
#include <sodium/crypto_pwhash.h>
#include <stdexcept>
#include <string>
#include <termios.h>
#include <unistd.h>
#include <unordered_map>
#include <vector>
